### ISSUE TITLE
Ability To Change The Speed Of Decrease

### ISSUE THREAD

**Issue by czhangdev** [HolyGolf/ThirstForWater#2]
Hey, It is a wonderful plugin of yours, I was just wondering, is there any chance that you could add the ability to change the speed of decrease of thirst in the configuration file? Thanks

**Comment by HolyGolf** [comment]
> Hey, It is a wonderful plugin of yours, I was just wondering, is there any chance that you could add the ability to change the speed of decrease of thirst in the configuration file? Thanks

Hey! Ok i will add this in the coming days.

**Comment by czhangdev** [comment]
Thanks, I will surely recommend this plugin to my friend and leave a good review. And btw, this plugin apparently works with 1.17 without issues.
