### ISSUE TITLE
Ability to recover thirst by eating

### ISSUE THREAD

**Issue by czhangdev** [HolyGolf/ThirstForWater#3]
Hey, I am really sorry if I am bothering you, but I have a new suggestion for the plugin, as the title said, the ability to recover thirst by eating certain type of food, for example, like apples, berries, etc.

**Comment by HolyGolf** [comment]
It's okay to bother me. You know, the idea sounds great. I will take note.

**Comment by czhangdev** [comment]
Thanks, it is great to know that such a great plugin have such a wonderful developer, surely tell this plugin to my friend too. Also, I left a 5-star review on the plugin, if I could, I would left a 10-star
